### ISSUE TITLE
Calling non-groovy script possible?

### ISSUE THREAD

**Issue by Vince-Cercury** [jenkinsci/templating-engine-plugin#73] opened 2020-04-28 06:12 UTC
From a library step, is it possible to make a call to a bash script or a python script which is stored inside the same repository as the groovy step(JTE library)?

Example, from a step
```
sh "my-custom-script.sh"
```

I added my-custom-script.sh at root of the repository (the one that contains the librairies) 
But I don't see any library related file in the workspace

**Comment by steven-terrana** [comment] 2020-04-30 12:50
hey @Vince-Cercury - sorry for the delay. 

This is a great idea, i'd probably call this a duplicate of https://github.com/jenkinsci/templating-engine-plugin/issues/46.

It's at the top of the backlog to be able to have the same `libraryResources` functionality that regular Jenkins Shared Libraries have.

**Comment by steven-terrana** [comment] 2020-04-30 12:54
Duplicate of #46

**Comment by steven-terrana** [comment] 2020-04-30 12:54
going to close this issue in favor of that one, feel free to hop over there and provide feedback!

**Closed by steven-terrana** 2020-04-30 12:54 UTC
