### ISSUE TITLE
Problems retrieving global Application Environments variables

### ISSUE THREAD

**Issue by carlosgv87** [jenkinsci/templating-engine-plugin#221] opened 2021-07-13 17:05 UTC
### Jenkins Version

2.289.2

### JTE Version

2.3

### Bug Description

I'm trying to migrate all my pipelines which are working on version `1.7.1` of `Templating Engine` plugin to version `2.3` ( for example, but it doesn't work with version `2.2.2`). I'm having troubles during the retrieval process of global variables defined on a global `pipeline_config.groovy` file from a step (`get_environment_variable.groovy`) defined on the `common` library.

As you could see at the beginning of the log below:
```
[JTE] -- file path: global/pipeline_config.groovy
[JTE] Pipeline Configuration Modifications 
[JTE] Configurations Added:
[JTE] - jte.allow_scm_jenkinsfile set to false
[JTE] - application_environments.development.country.es.country_code set to es
[JTE] - application_environments.development.country.es.country_name set to Spain
[JTE] - application_environments.development.country.es.aws_region set to eu-west-1
[JTE] - application_environments.development.country.es.aws_environment_account_id set to 111111111111
[JTE] - application_environments.development.country.es.aws_infrastructure_provider_role set to TestRole
[JTE] - application_environments.development.country.es.long_name set to Development
[JTE] - application_environments.development.country.es.short_name set to dev
[JTE] - application_environments.development.country.es.k8s_credentials_id set to kube-es-dev
[JTE] - application_environments.development.country.es.batch_helm_chart.name set to batch-helm-chart
[JTE] - application_environments.development.country.es.batch_helm_chart.version set to 1.0.0
[JTE] - application_environments.development.country.es.microservice_helm_chart.name set to microservice-helm-chart
[JTE] - application_environments.development.country.es.microservice_helm_chart.version set to 1.0.0
[JTE] - application_environments.development.country.es.helm_global_values.name set to helm-global-values-dev
[JTE] - application_environments.development.country.es.helm_global_values.version set to 1.0.0
[JTE] - application_environments.integration.country.es.country_code set to es
[JTE] - application_environments.integration.country.es.country_name set to Spain
[JTE] - application_environments.integration.country.es.aws_region set to eu-west-1
[JTE] - application_environments.integration.country.es.aws_environment_account_id set to 222222222222
[JTE] - application_environments.integration.country.es.aws_infrastructure_provider_role set to TestRole
[JTE] - application_environments.integration.country.es.long_name set to Integration
[JTE] - application_environments.integration.country.es.short_name set to int
[JTE] - application_environments.integration.country.es.k8s_credentials_id set to kube-es-int
[JTE] - application_environments.integration.country.es.batch_helm_chart.name set to batch-helm-chart
[JTE] - application_environments.integration.country.es.batch_helm_chart.version set to 1.0.0
[JTE] - application_environments.integration.country.es.microservice_helm_chart.name set to microservice-helm-chart
[JTE] - application_environments.integration.country.es.microservice_helm_chart.version set to 1.0.0
[JTE] - application_environments.integration.country.es.helm_global_values.name set to helm-global-values-int
[JTE] - application_environments.integration.country.es.helm_global_values.version set to 1.0.0
[JTE] - application_environments.preproduction.country.es.country_code set to es
[JTE] - application_environments.preproduction.country.es.country_name set to Spain
[JTE] - application_environments.preproduction.country.es.aws_region set to eu-west-1
[JTE] - application_environments.preproduction.country.es.aws_environment_account_id set to 333333333333
[JTE] - application_environments.preproduction.country.es.aws_infrastructure_provider_role set to TestRole
[JTE] - application_environments.preproduction.country.es.long_name set to Preproduction
[JTE] - application_environments.preproduction.country.es.short_name set to pre
[JTE] - application_environments.preproduction.country.es.k8s_credentials_id set to kube-es-pre
[JTE] - application_environments.preproduction.country.es.batch_helm_chart.name set to batch-helm-chart
[JTE] - application_environments.preproduction.country.es.batch_helm_chart.version set to 1.0.0
[JTE] - application_environments.preproduction.country.es.microservice_helm_chart.name set to microservice-helm-chart
[JTE] - application_environments.preproduction.country.es.microservice_helm_chart.version set to 1.0.0
[JTE] - application_environments.preproduction.country.es.helm_global_values.name set to helm-global-values-pre
[JTE] - application_environments.preproduction.country.es.helm_global_values.version set to 1.0.0
[JTE] - application_environments.production.country.es.country_code set to es
[JTE] - application_environments.production.country.es.country_name set to Spain
[JTE] - application_environments.production.country.es.aws_region set to eu-west-1
[JTE] - application_environments.production.country.es.aws_environment_account_id set to 444444444444
[JTE] - application_environments.production.country.es.aws_infrastructure_provider_role set to TestRole
[JTE] - application_environments.production.country.es.long_name set to Production
[JTE] - application_environments.production.country.es.short_name set to pro
[JTE] - application_environments.production.country.es.k8s_credentials_id set to kube-es-pro
[JTE] - application_environments.production.country.es.batch_helm_chart.name set to batch-helm-chart
[JTE] - application_environments.production.country.es.batch_helm_chart.version set to 1.0.0
[JTE] - application_environments.production.country.es.microservice_helm_chart.name set to microservice-helm-chart
[JTE] - application_environments.production.country.es.microservice_helm_chart.version set to 1.0.0
[JTE] - application_environments.production.country.es.helm_global_values.name set to helm-global-values-pro
[JTE] - application_environments.production.country.es.helm_global_values.version set to 1.0.0
[JTE] - libraries.commons.aws_region set to eu-west-1
[JTE] - libraries.commons.aws_master_account_id set to 000000000000
[JTE] - libraries.commons.aws_infrastructure_provider_role set to TestRole
[JTE] - libraries.commons.sonar_qg_timeout_in_minutes set to 3
```
It seems that the global variables are injected, but after all libraries are loaded, the job fails saying this:

```
[Pipeline] End of Pipeline
hudson.remoting.ProxyException: groovy.lang.MissingPropertyException: No such property: development for class: org.boozallen.plugins.jte.init.primitives.TemplateBinding
```

### Relevant log output

```shell
[JTE] Obtained Pipeline Configuration File 
[JTE] -- scm: git https://github.com/carlosgv87/jte-pipeline-governance-tier.git
[JTE] -- file path: global/pipeline_config.groovy
[JTE] Pipeline Configuration Modifications 
[JTE] Configurations Added:
[JTE] - jte.allow_scm_jenkinsfile set to false
[JTE] - application_environments.development.country.es.country_code set to es
[JTE] - application_environments.development.country.es.country_name set to Spain
[JTE] - application_environments.development.country.es.aws_region set to eu-west-1
[JTE] - application_environments.development.country.es.aws_environment_account_id set to 111111111111
[JTE] - application_environments.development.country.es.aws_infrastructure_provider_role set to TestRole
[JTE] - application_environments.development.country.es.long_name set to Development
[JTE] - application_environments.development.country.es.short_name set to dev
[JTE] - application_environments.development.country.es.k8s_credentials_id set to kube-es-dev
[JTE] - application_environments.development.country.es.batch_helm_chart.name set to batch-helm-chart
[JTE] - application_environments.development.country.es.batch_helm_chart.version set to 1.0.0
[JTE] - application_environments.development.country.es.microservice_helm_chart.name set to microservice-helm-chart
[JTE] - application_environments.development.country.es.microservice_helm_chart.version set to 1.0.0
[JTE] - application_environments.development.country.es.helm_global_values.name set to helm-global-values-dev
[JTE] - application_environments.development.country.es.helm_global_values.version set to 1.0.0
[JTE] - application_environments.integration.country.es.country_code set to es
[JTE] - application_environments.integration.country.es.country_name set to Spain
[JTE] - application_environments.integration.country.es.aws_region set to eu-west-1
[JTE] - application_environments.integration.country.es.aws_environment_account_id set to 222222222222
[JTE] - application_environments.integration.country.es.aws_infrastructure_provider_role set to TestRole
[JTE] - application_environments.integration.country.es.long_name set to Integration
[JTE] - application_environments.integration.country.es.short_name set to int
[JTE] - application_environments.integration.country.es.k8s_credentials_id set to kube-es-int
[JTE] - application_environments.integration.country.es.batch_helm_chart.name set to batch-helm-chart
[JTE] - application_environments.integration.country.es.batch_helm_chart.version set to 1.0.0
[JTE] - application_environments.integration.country.es.microservice_helm_chart.name set to microservice-helm-chart
[JTE] - application_environments.integration.country.es.microservice_helm_chart.version set to 1.0.0
[JTE] - application_environments.integration.country.es.helm_global_values.name set to helm-global-values-int
[JTE] - application_environments.integration.country.es.helm_global_values.version set to 1.0.0
[JTE] - application_environments.preproduction.country.es.country_code set to es
[JTE] - application_environments.preproduction.country.es.country_name set to Spain
[JTE] - application_environments.preproduction.country.es.aws_region set to eu-west-1
[JTE] - application_environments.preproduction.country.es.aws_environment_account_id set to 333333333333
[JTE] - application_environments.preproduction.country.es.aws_infrastructure_provider_role set to TestRole
[JTE] - application_environments.preproduction.country.es.long_name set to Preproduction
[JTE] - application_environments.preproduction.country.es.short_name set to pre
[JTE] - application_environments.preproduction.country.es.k8s_credentials_id set to kube-es-pre
[JTE] - application_environments.preproduction.country.es.batch_helm_chart.name set to batch-helm-chart
[JTE] - application_environments.preproduction.country.es.batch_helm_chart.version set to 1.0.0
[JTE] - application_environments.preproduction.country.es.microservice_helm_chart.name set to microservice-helm-chart
[JTE] - application_environments.preproduction.country.es.microservice_helm_chart.version set to 1.0.0
[JTE] - application_environments.preproduction.country.es.helm_global_values.name set to helm-global-values-pre
[JTE] - application_environments.preproduction.country.es.helm_global_values.version set to 1.0.0
[JTE] - application_environments.production.country.es.country_code set to es
[JTE] - application_environments.production.country.es.country_name set to Spain
[JTE] - application_environments.production.country.es.aws_region set to eu-west-1
[JTE] - application_environments.production.country.es.aws_environment_account_id set to 444444444444
[JTE] - application_environments.production.country.es.aws_infrastructure_provider_role set to TestRole
[JTE] - application_environments.production.country.es.long_name set to Production
[JTE] - application_environments.production.country.es.short_name set to pro
[JTE] - application_environments.production.country.es.k8s_credentials_id set to kube-es-pro
[JTE] - application_environments.production.country.es.batch_helm_chart.name set to batch-helm-chart
[JTE] - application_environments.production.country.es.batch_helm_chart.version set to 1.0.0
[JTE] - application_environments.production.country.es.microservice_helm_chart.name set to microservice-helm-chart
[JTE] - application_environments.production.country.es.microservice_helm_chart.version set to 1.0.0
[JTE] - application_environments.production.country.es.helm_global_values.name set to helm-global-values-pro
[JTE] - application_environments.production.country.es.helm_global_values.version set to 1.0.0
[JTE] - libraries.commons.aws_region set to eu-west-1
[JTE] - libraries.commons.aws_master_account_id set to 000000000000
[JTE] - libraries.commons.aws_infrastructure_provider_role set to TestRole
[JTE] - libraries.commons.sonar_qg_timeout_in_minutes set to 3
[JTE] - libraries.bitbucket set to [:]
[JTE] - libraries.office365 set to [:]
[JTE] Configurations Deleted: None
[JTE] Configurations Changed: None
[JTE] Configurations Duplicated: None
[JTE] Configurations Ignored: None
[JTE] Subsequent May Merge:
[JTE] - libraries
[JTE] Subsequent May Override: None
[JTE] Obtained Pipeline Configuration File 
[JTE] -- scm: git https://github.com/carlosgv87/jte-pipeline-governance-tier.git
[JTE] -- file path: microservices-ops/pipeline_config.groovy
[JTE] Pipeline Configuration Modifications 
[JTE] Configurations Added:
[JTE] - libraries.helm set to [:]
[JTE] - libraries.microservice set to [:]
[JTE] Configurations Deleted: None
[JTE] Configurations Changed: None
[JTE] Configurations Duplicated: None
[JTE] Configurations Ignored: None
[JTE] Subsequent May Merge: None
[JTE] Subsequent May Override: None
18:16:51 Connecting to https://api.github.com with no credentials, anonymous access
[JTE] Loading Library commons 
[JTE] -- scm: git https://github.com/carlosgv87/jte-pipeline-library.git
[JTE] Loading Library bitbucket 
[JTE] -- scm: git https://github.com/carlosgv87/jte-pipeline-library.git
[JTE] Loading Library office365 
[JTE] -- scm: git https://github.com/carlosgv87/jte-pipeline-library.git
[JTE] Loading Library helm 
[JTE] -- scm: git https://github.com/carlosgv87/jte-pipeline-library.git
[JTE] Loading Library microservice 
[JTE] -- scm: git https://github.com/carlosgv87/jte-pipeline-library.git
[JTE] Obtained Template 
[JTE] -- scm: git https://github.com/carlosgv87/jte-pipeline-governance-tier.git
[JTE] -- file path: microservices-ops/Jenkinsfile
Running in Durability level: MAX_SURVIVABILITY
[Pipeline] Start of Pipeline
[JTE][Step - bitbucket/isPR.call()]
[JTE][Step - commons/get_environment_data.call(String)]
[JTE][Step - commons/log.debug(String)]
[Pipeline] echo
[DEBUG] binding: org.boozallen.plugins.jte.init.primitives.TemplateBinding@1b5dd3b4
[JTE][Step - commons/log.debug(String)]
[Pipeline] echo
[DEBUG] binding.variables: [steps:org.jenkinsci.plugins.workflow.cps.DSL@5b055324]
[JTE][Step - commons/log.debug(String)]
[Pipeline] echo
[DEBUG] binding.getProperties(): [class:class org.boozallen.plugins.jte.init.primitives.TemplateBinding, variables:[steps:org.jenkinsci.plugins.workflow.cps.DSL@5b055324]]
[JTE][Step - commons/log.debug(String)]
[Pipeline] echo
[DEBUG] jte.application_environments: org.boozallen.plugins.jte.init.primitives.TemplatePrimitiveNamespace@232ff99d
[JTE][Step - commons/log.debug(String)]
[Pipeline] echo
[DEBUG] jte.application_environments.environment_name: Application Environment 'development'
[Pipeline] End of Pipeline
hudson.remoting.ProxyException: groovy.lang.MissingPropertyException: No such property: development for class: org.boozallen.plugins.jte.init.primitives.TemplateBinding
	at groovy.lang.Binding.getVariable(Binding.java:63)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1213)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:42)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at com.cloudbees.groovy.cps.sandbox.DefaultInvoker.methodCall(DefaultInvoker.java:20)
	at WorkflowScript.call(WorkflowScript:7)
	at org.boozallen.plugins.jte.init.primitives.injectors.StepWrapperCPS.methodMissing(script16261930409201204730961.groovy:59)
	at WorkflowScript.run(WorkflowScript:3)
	at ___cps.transform___(Native Method)
	at com.cloudbees.groovy.cps.impl.ContinuationGroup.methodCall(ContinuationGroup.java:86)
	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.dispatchOrArg(FunctionCallBlock.java:113)
Caused: hudson.remoting.ProxyException: org.codehaus.groovy.runtime.InvokerInvocationException: groovy.lang.MissingPropertyException: No such property: development for class: org.boozallen.plugins.jte.init.primitives.TemplateBinding
	at org.boozallen.plugins.jte.init.primitives.injectors.StepWrapperCPS.methodMissing(script16261930409201204730961.groovy:61)
	at WorkflowScript.run(WorkflowScript:3)
	at ___cps.transform___(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:83)
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:105)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:60)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:235)
	at com.cloudbees.groovy.cps.sandbox.DefaultInvoker.constructorCall(DefaultInvoker.java:25)
	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.dispatchOrArg(FunctionCallBlock.java:97)
	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.fixArg(FunctionCallBlock.java:83)
	at jdk.internal.reflect.GeneratedMethodAccessor316.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
	at com.cloudbees.groovy.cps.impl.LocalVariableBlock$LocalVariable.get(LocalVariableBlock.java:39)
	at com.cloudbees.groovy.cps.LValueBlock$GetAdapter.receive(LValueBlock.java:30)
	at com.cloudbees.groovy.cps.impl.LocalVariableBlock.evalLValue(LocalVariableBlock.java:28)
	at com.cloudbees.groovy.cps.LValueBlock$BlockImpl.eval(LValueBlock.java:55)
	at com.cloudbees.groovy.cps.LValueBlock.eval(LValueBlock.java:16)
	at com.cloudbees.groovy.cps.Next.step(Next.java:83)
	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:174)
	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:163)
	at org.codehaus.groovy.runtime.GroovyCategorySupport$ThreadCategoryInfo.use(GroovyCategorySupport.java:129)
	at org.codehaus.groovy.runtime.GroovyCategorySupport.use(GroovyCategorySupport.java:268)
	at com.cloudbees.groovy.cps.Continuable.run0(Continuable.java:163)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.access$001(SandboxContinuable.java:18)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.run0(SandboxContinuable.java:51)
	at org.jenkinsci.plugins.workflow.cps.CpsThread.runNextChunk(CpsThread.java:185)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run(CpsThreadGroup.java:400)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.access$400(CpsThreadGroup.java:96)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:312)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:276)
	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$2.call(CpsVmExecutorService.java:67)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:139)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:68)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Finished: FAILURE
```

### Steps to Reproduce

These are 2 repositories (https://github.com/carlosgv87/jte-pipeline-governance-tier and https://github.com/carlosgv87/jte-pipeline-library) with an example of 2 pipelines (`microservices-build` and `microservices-ops`) and the libraries used by these pipelines. `microservices-ops` is the one which isn't working.

In order to reproduce this error you need to follow these steps:

1. Replicate this Jenkins global configuration related to `Templating Engine` plugin:

![jenkins-global-jte-config_pipeline-configuration](https://user-images.githubusercontent.com/19566246/125494017-f160600c-e18c-467a-ae1c-ef1d9ce4ada0.png)

![jenkins-global-jte-config_library-resources](https://user-images.githubusercontent.com/19566246/125494037-3b417006-c52c-4d2d-b23a-85e065e080c0.png)

2. Create a `Multibranch Pipeline` job with this configuration:
- Source repository: https://github.com/carlosgv87/maven-test-repo-ops.git

![maven-test-repo-ops-config_sources](https://user-images.githubusercontent.com/19566246/125494944-49d27381-f14e-4a6b-ae6c-4145fdd1eb17.png)

![maven-test-repo-ops-config_behaviours](https://user-images.githubusercontent.com/19566246/125494389-355f0326-0a62-433e-ba8c-d184a215c058.png)

![maven-test-repo-ops-config_build-configuration](https://user-images.githubusercontent.com/19566246/125494406-3af258b4-bd04-43fa-9199-4767bf7ce6ce.png)

![maven-test-repo-ops-config_jte-pipeline-configuration](https://user-images.githubusercontent.com/19566246/125494428-e38d9f77-f916-4639-b521-0ac7e6b99d4c.png)

![maven-test-repo-ops-config_jte-library-sources](https://user-images.githubusercontent.com/19566246/125494443-f729367a-608b-4aed-9b98-c0f3860ed9a7.png)

3. Run job for `development` branch.

**Comment by jmsanchez** [comment] 2021-07-14 06:59
We have the same problem using another Jenkins version :(

**Comment by wolfishsoul** [comment] 2021-07-14 07:08
I am experiencing the same problem for a while now...using another version of Jenkins. Can't seem to find a solution online!

**Comment by steven-terrana** [comment] 2021-07-14 12:49
thanks for reporting! i'll take a look as soon as i can.

**Comment by cokieffebah** [comment] 2021-07-14 12:54
the end of `commons/steps/get_environment_data.groovy` is `binding.getVariable(environment_name)` which is not the same as return jte.application_environments.development.  unless you added a development variable to the binding for that library, it would not find `binding.development`

**Comment by carlosgv87** [comment] 2021-07-14 13:41
@cokieffebah, I have tested it on version `2.2.2` of `Templating Engine` plugin, and it's doesn't work either.

Could you please help me with this?

**Comment by cokieffebah** [comment] 2021-07-14 13:52
I am assuming the issue is what I stated above, not being snarky but you did not address my comment, so did you try changing the code for get_environment_data.groovy to :
```
Object call(String environment_name) {
    log.debug("binding: " + binding)
    log.debug("binding.variables: " + binding.variables)
    log.debug("binding.getProperties(): " + binding.getProperties())
    log.debug("jte.application_environments: " + jte.application_environments)
    log.debug("jte.application_environments.environment_name: " + jte.application_environments."${environment_name}")
    return jte.application_environments."${environment_name}"  // binding.getVariable(environment_name)
}
```

**Comment by cokieffebah** [comment] 2021-07-14 18:26
@carlosgv87 ^

**Comment by carlosgv87** [comment] 2021-07-14 22:41
Hi @cokieffebah, I am testing your suggested change and the initial reported error it's solved, but now I have some other errors that I am investigating. If you don't mind keeping this issue opened I will be writing back with further information about those new problems.

Thanks in advance 😃

**Comment by cokieffebah** [comment] 2021-11-03 20:48
been a while, I am closing this issue

**Closed by cokieffebah** 2021-11-03 20:48 UTC
Labels: bug
