### ISSUE TITLE
[Bug]: Templating sometimes fails with cast/constructor error

### ISSUE THREAD

**Issue by andrewm-aero** [jenkinsci/templating-engine-plugin#250] opened 2021-12-16 17:35 UTC
### Jenkins Version

2.303.1

### JTE Version

2.2.2

### Bug Description

Under certain circumstances which we have yet to isolate, pipeline templating fails with cast errors from the groovy runtime. We have found that the presence or absence of one of our newer JTE libraries causes the error, but we are unable to share this library at the moment without going through a lengthy code-release process due to corporate policy. We don't believe the library is using any features outside of those described in the documentation (steps with call() function, library_config.groovy with optional and required fields, etc) We also found that re-naming our step "build" to "build_" changes the error produced. Not all pipelines fail with this error, and we are still working on identifying the root cause. Affected pipelines seem to always fail, and unaffected pipelines seem to always pass.

### Relevant log output

```shell
(Without primitive name conflict)

[JTE] Cannot cast object '[]' with class 'java.util.LinkedHashSet' to class 'java.util.List' due to: groovy.lang.GroovyRuntimeException: Could not find matching constructor for: java.util.List() 
[JTE] org.codehaus.groovy.runtime.typehandling.DefaultTypeTransformation.continueCastOnSAM(DefaultTypeTransformation.java:403)
[JTE] org.codehaus.groovy.runtime.typehandling.DefaultTypeTransformation.continueCastOnNumber(DefaultTypeTransformation.java:319)
[JTE] org.codehaus.groovy.runtime.typehandling.DefaultTypeTransformation.continueCastOnCollection(DefaultTypeTransformation.java:267)
[JTE] org.codehaus.groovy.runtime.typehandling.DefaultTypeTransformation.castToType(DefaultTypeTransformation.java:219)
[JTE] org.codehaus.groovy.runtime.ScriptBytecodeAdapter.castToType(ScriptBytecodeAdapter.java:603)
[JTE] org.boozallen.plugins.jte.init.primitives.injectors.GlobalCollisionValidator.checkForJenkinsStepCollisions(GlobalCollisionValidator.groovy:98)
[JTE] org.boozallen.plugins.jte.init.primitives.injectors.GlobalCollisionValidator$checkForJenkinsStepCollisions$1.callCurrent(Unknown Source)
[JTE] org.boozallen.plugins.jte.init.primitives.injectors.GlobalCollisionValidator.validatePrimitives(GlobalCollisionValidator.groovy:50)
[JTE] java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[JTE] java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[JTE] java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[JTE] java.base/java.lang.reflect.Method.invoke(Method.java:566)
[JTE] org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
[JTE] groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
[JTE] groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1213)
[JTE] groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
[JTE] groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:810)
[JTE] org.boozallen.plugins.jte.init.primitives.TemplatePrimitiveInjector.invokeMethod(TemplatePrimitiveInjector.groovy)
[JTE] groovy.lang.GroovyObject$invokeMethod.call(Unknown Source)
[JTE] org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
[JTE] groovy.lang.GroovyObject$invokeMethod.call(Unknown Source)
[JTE] org.boozallen.plugins.jte.init.primitives.TemplatePrimitiveInjector$_invoke_closure1.doCall(TemplatePrimitiveInjector.groovy:144)
[JTE] jdk.internal.reflect.GeneratedMethodAccessor2187.invoke(Unknown Source)
[JTE] java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[JTE] java.base/java.lang.reflect.Method.invoke(Method.java:566)
[JTE] org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
[JTE] groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
[JTE] org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
[JTE] groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
[JTE] groovy.lang.Closure.call(Closure.java:414)
[JTE] groovy.lang.Closure.call(Closure.java:430)
[JTE] org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2040)
[JTE] org.codehaus.groovy.runtime.dgm$162.invoke(Unknown Source)
[JTE] org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:274)
[JTE] org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:56)
[JTE] org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
[JTE] org.boozallen.plugins.jte.init.primitives.TemplatePrimitiveInjector.invoke(TemplatePrimitiveInjector.groovy:139)
[JTE] java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[JTE] java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[JTE] java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[JTE] java.base/java.lang.reflect.Method.invoke(Method.java:566)
[JTE] org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
[JTE] groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
[JTE] org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite.invoke(StaticMetaMethodSite.java:46)
[JTE] org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite.callStatic(StaticMetaMethodSite.java:102)
[JTE] org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:222)
[JTE] org.boozallen.plugins.jte.init.primitives.TemplatePrimitiveInjector.orchestrate(TemplatePrimitiveInjector.groovy:89)
[JTE] org.boozallen.plugins.jte.init.primitives.TemplatePrimitiveInjector$orchestrate$6.call(Unknown Source)
[JTE] org.boozallen.plugins.jte.init.PipelineDecorator.initialize(PipelineDecorator.groovy:62)
[JTE] org.boozallen.plugins.jte.init.PipelineDecorator$initialize.call(Unknown Source)
[JTE] org.boozallen.plugins.jte.job.TemplateFlowDefinition.initializeJTE(TemplateFlowDefinition.groovy:60)
[JTE] java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[JTE] java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[JTE] java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[JTE] java.base/java.lang.reflect.Method.invoke(Method.java:566)
[JTE] org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:210)
[JTE] org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:59)
[JTE] org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:166)
[JTE] org.boozallen.plugins.jte.job.TemplateFlowDefinition.create(TemplateFlowDefinition.groovy:54)
[JTE] org.jenkinsci.plugins.workflow.job.WorkflowRun.run(WorkflowRun.java:309)
[JTE] hudson.model.ResourceController.execute(ResourceController.java:100)
[JTE] hudson.model.Executor.run(Executor.java:433)
org.boozallen.plugins.jte.util.AggregateException: The following errors occurred: 
1: Cannot cast object '[]' with class 'java.util.LinkedHashSet' to class 'java.util.List' due to: groovy.lang.GroovyRuntimeException: Could not find matching constructor for: java.util.List()
	at jdk.internal.reflect.GeneratedConstructorAccessor475.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:83)
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:105)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:239)
	at org.boozallen.plugins.jte.init.primitives.TemplatePrimitiveInjector.invoke(TemplatePrimitiveInjector.groovy:138)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite.invoke(StaticMetaMethodSite.java:46)
	at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite.callStatic(StaticMetaMethodSite.java:102)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:222)
	at org.boozallen.plugins.jte.init.primitives.TemplatePrimitiveInjector.orchestrate(TemplatePrimitiveInjector.groovy:89)
	at org.boozallen.plugins.jte.init.primitives.TemplatePrimitiveInjector$orchestrate$6.call(Unknown Source)
	at org.boozallen.plugins.jte.init.PipelineDecorator.initialize(PipelineDecorator.groovy:62)
	at org.boozallen.plugins.jte.init.PipelineDecorator$initialize.call(Unknown Source)
	at org.boozallen.plugins.jte.job.TemplateFlowDefinition.initializeJTE(TemplateFlowDefinition.groovy:60)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:210)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:59)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:166)
	at org.boozallen.plugins.jte.job.TemplateFlowDefinition.create(TemplateFlowDefinition.groovy:54)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun.run(WorkflowRun.java:309)
	at hudson.model.ResourceController.execute(ResourceController.java:100)
	at hudson.model.Executor.run(Executor.java:433)
Finished: FAILURE


(With primitive name conflict)

[JTE] Cannot cast object '[build]' with class 'java.util.LinkedHashSet' to class 'java.util.List' due to: groovy.lang.GroovyRuntimeException: Could not find matching constructor for: java.util.List(java.lang.String) 
[JTE] org.codehaus.groovy.runtime.typehandling.DefaultTypeTransformation.continueCastOnSAM(DefaultTypeTransformation.java:403)
[JTE] org.codehaus.groovy.runtime.typehandling.DefaultTypeTransformation.continueCastOnNumber(DefaultTypeTransformation.java:319)
[JTE] org.codehaus.groovy.runtime.typehandling.DefaultTypeTransformation.continueCastOnCollection(DefaultTypeTransformation.java:267)
[JTE] org.codehaus.groovy.runtime.typehandling.DefaultTypeTransformation.castToType(DefaultTypeTransformation.java:219)
[JTE] org.codehaus.groovy.runtime.ScriptBytecodeAdapter.castToType(ScriptBytecodeAdapter.java:603)
[JTE] org.boozallen.plugins.jte.init.primitives.injectors.GlobalCollisionValidator.checkForJenkinsStepCollisions(GlobalCollisionValidator.groovy:98)
[JTE] org.boozallen.plugins.jte.init.primitives.injectors.GlobalCollisionValidator$checkForJenkinsStepCollisions$1.callCurrent(Unknown Source)
[JTE] org.boozallen.plugins.jte.init.primitives.injectors.GlobalCollisionValidator.validatePrimitives(GlobalCollisionValidator.groovy:50)
[JTE] java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[JTE] java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[JTE] java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[JTE] java.base/java.lang.reflect.Method.invoke(Method.java:566)
[JTE] org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
[JTE] groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
[JTE] groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1213)
[JTE] groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
[JTE] groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:810)
[JTE] org.boozallen.plugins.jte.init.primitives.TemplatePrimitiveInjector.invokeMethod(TemplatePrimitiveInjector.groovy)
[JTE] groovy.lang.GroovyObject$invokeMethod.call(Unknown Source)
[JTE] org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
[JTE] groovy.lang.GroovyObject$invokeMethod.call(Unknown Source)
[JTE] org.boozallen.plugins.jte.init.primitives.TemplatePrimitiveInjector$_invoke_closure1.doCall(TemplatePrimitiveInjector.groovy:144)
[JTE] jdk.internal.reflect.GeneratedMethodAccessor984.invoke(Unknown Source)
[JTE] java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[JTE] java.base/java.lang.reflect.Method.invoke(Method.java:566)
[JTE] org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
[JTE] groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
[JTE] org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
[JTE] groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
[JTE] groovy.lang.Closure.call(Closure.java:414)
[JTE] groovy.lang.Closure.call(Closure.java:430)
[JTE] org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2040)
[JTE] org.codehaus.groovy.runtime.dgm$162.invoke(Unknown Source)
[JTE] org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:274)
[JTE] org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:56)
[JTE] org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
[JTE] org.boozallen.plugins.jte.init.primitives.TemplatePrimitiveInjector.invoke(TemplatePrimitiveInjector.groovy:139)
[JTE] java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[JTE] java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[JTE] java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[JTE] java.base/java.lang.reflect.Method.invoke(Method.java:566)
[JTE] org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
[JTE] groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
[JTE] org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite.invoke(StaticMetaMethodSite.java:46)
[JTE] org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite.callStatic(StaticMetaMethodSite.java:102)
[JTE] org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:222)
[JTE] org.boozallen.plugins.jte.init.primitives.TemplatePrimitiveInjector.orchestrate(TemplatePrimitiveInjector.groovy:89)
[JTE] org.boozallen.plugins.jte.init.primitives.TemplatePrimitiveInjector$orchestrate.call(Unknown Source)
[JTE] org.boozallen.plugins.jte.init.PipelineDecorator.initialize(PipelineDecorator.groovy:62)
[JTE] org.boozallen.plugins.jte.init.PipelineDecorator$initialize.call(Unknown Source)
[JTE] org.boozallen.plugins.jte.job.TemplateFlowDefinition.initializeJTE(TemplateFlowDefinition.groovy:60)
[JTE] java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[JTE] java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[JTE] java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[JTE] java.base/java.lang.reflect.Method.invoke(Method.java:566)
[JTE] org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:210)
[JTE] org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:59)
[JTE] org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:166)
[JTE] org.boozallen.plugins.jte.job.TemplateFlowDefinition.create(TemplateFlowDefinition.groovy:54)
[JTE] org.jenkinsci.plugins.workflow.job.WorkflowRun.run(WorkflowRun.java:309)
[JTE] hudson.model.ResourceController.execute(ResourceController.java:100)
[JTE] hudson.model.Executor.run(Executor.java:433)
org.boozallen.plugins.jte.util.AggregateException: The following errors occurred: 
1: Cannot cast object '[build]' with class 'java.util.LinkedHashSet' to class 'java.util.List' due to: groovy.lang.GroovyRuntimeException: Could not find matching constructor for: java.util.List(java.lang.String)
	at jdk.internal.reflect.GeneratedConstructorAccessor475.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:83)
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:105)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:239)
	at org.boozallen.plugins.jte.init.primitives.TemplatePrimitiveInjector.invoke(TemplatePrimitiveInjector.groovy:138)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite.invoke(StaticMetaMethodSite.java:46)
	at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite.callStatic(StaticMetaMethodSite.java:102)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:222)
	at org.boozallen.plugins.jte.init.primitives.TemplatePrimitiveInjector.orchestrate(TemplatePrimitiveInjector.groovy:89)
	at org.boozallen.plugins.jte.init.primitives.TemplatePrimitiveInjector$orchestrate.call(Unknown Source)
	at org.boozallen.plugins.jte.init.PipelineDecorator.initialize(PipelineDecorator.groovy:62)
	at org.boozallen.plugins.jte.init.PipelineDecorator$initialize.call(Unknown Source)
	at org.boozallen.plugins.jte.job.TemplateFlowDefinition.initializeJTE(TemplateFlowDefinition.groovy:60)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:210)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:59)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:166)
	at org.boozallen.plugins.jte.job.TemplateFlowDefinition.create(TemplateFlowDefinition.groovy:54)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun.run(WorkflowRun.java:309)
	at hudson.model.ResourceController.execute(ResourceController.java:100)
	at hudson.model.Executor.run(Executor.java:433)
Finished: FAILURE
```

### Steps to Reproduce

Under investigation

**Comment by andrewm-aero** [comment] 2021-12-18 22:20
Update: Still working on narrowing down the exact cause and producing a minimal reproducible example, but it appears to be correlated with the presence/absence of a step file in one our libraries called `promote_config.groovy`. Even reducing this file's contents to just `void call(){}' or even empty entirely does not prevent the error, only removing the file entirely causes the error to go away. Re-adding an empty file with the same same causes the error to return. Unsure if this name has any significance, but it doesn't seem to appear anywhere in the codebase.

**Comment by andrewm-aero** [comment] 2021-12-20 16:12
The pipeline template is composed of just the steps, without any sort of extra behavior, or arguments to any of the step call() functions. The one exception to this rule is that this those step are passed via lambda function to a step that constructs a kubernetes agent pod based on the steps in it. We also tried it with a hard-coded agent instead and the error persists. The whole things look like this
```groovy
with_agent() {
  stage('foo') {
    foo()
  }
  stage('bar') {
    bar()
  }
  // ...
}
```
Where with_agent() is a wrapper around podTemplate() and node().

One thing I realized I neglected to mention is that we are using `permissive_initialization` in our pipeline_config.groovy files, and haven't tried without that yet, as some of our libraries depend on it.

**Comment by cokieffebah** [comment] 2021-12-20 16:17
hmm, reading the error,  something is trying to cast a Set to List and those interfaces are not compatible ... much less those implementations.  LinkedHashSet is roughly a HashMap internally and 
` Cannot cast object '[build]' with class 'java.util.LinkedHashSet' to class 'java.util.List' due to: groovy.lang.GroovyRuntimeException: Could not find matching constructor for: java.util.List(java.lang.String)`

**Comment by cokieffebah** [comment] 2021-12-20 16:20
if you are using permissive_initialization, and there a base name collisions,  you might want to refer to steps specifically by their namespace: https://boozallen.github.io/sdp-docs/jte/2.2.2/primitives/primitive_namespace.html:
`jte.libraries.<library_name>.<library_step>()`

**Comment by andrewm-aero** [comment] 2021-12-20 16:31
Yes, we do in fact use the primitive namespace in the steps where it matters, but thank you for the info. As for the actual error message, I took a look at the code, and it seems to be trying to take an intersection of a list and set, and then cast that to a list interface. Somehow, its getting converted to a string before being converted to a list, which I suspect may be due to some eccentricities in how groovy auto-casts types due to being a dynamically typed language. As for why this happens differently based on what steps are loaded is beyond me. I'm not an expect in the language, but I would think casting to a concrete type, not an interface, specifically one with a constructor that accepts any collection, e.g. [this one](https://docs.oracle.com/javase/8/docs/api/java/util/ArrayList.html#ArrayList-java.util.Collection-) would solve this issue, but we haven't had the time to try and build and deploy the plugin from source ourselves.

**Comment by cokieffebah** [comment] 2021-12-20 16:34
I would do the intersect via Set.retainAll, if I remember correctly

**Comment by andrewm-aero** [comment] 2022-01-26 20:15
This issue has resurfaced in some of our new pipelines, with seemingly no cause, even without that file that was causing problems previously. Absolutely no idea what causes this.

**Comment by andrewm-aero** [comment] 2022-01-26 21:28
I finally got around to building from source, this patch made the newly failing pipeline run again, but I honestly can't say if that is because this fixed this issue, or if the patch just jostled something loose enough for it to work.

https://gist.github.com/andrewm-aero/be17a6a6e6b35624f96a1a673e5aba58

**Comment by steven-terrana** [comment] 2022-01-26 21:40
Thanks for working on this @andrewm-aero - i'll try to get a test case that reproduces the problem and confirm the fix. 

i was looking at this a few days ago and was stepping through with a debugger... trying to figure out a primitive name (library step name..) that causes things to get angry.

**Comment by cokieffebah** [comment] 2022-01-26 21:53
thanks @andrewm-aero  
in the current code:
List<String> stepCollisions = primitivesByName.keySet().intersect(functionNames)

`primitivesByName.keySet().intersect(functionNames)` [should result in a Set](https://docs.groovy-lang.org/latest/html/groovy-jdk/java/util/Set.html#intersect(java.lang.Iterable))
but I am assigning it to a List

**Comment by andrewm-aero** [comment] 2022-01-26 21:57
My best guess is that the primitive name is a red herring, as we've seen the issue with and without that promote_config step, and instead, there is likely something about a particular combination of configs and libraries puts the groovy runtime in a state where it will or won't cast the way that results in an error. Truly the worst kind of heisenbug.

Based on the error message

> Cannot cast object '[build]' with class 'java.util.LinkedHashSet' to class 'java.util.List' due to: groovy.lang.GroovyRuntimeException: Could not find matching constructor for: java.util.List(java.lang.String)

We can tell that `primitivesByName.keySet().intersect(functionNames)` returns a `java.util.LinkedHashSet`, which should be castable to `java.util.List` by first casting to something like `Collection` and then passing that to the constructor to `ArrayList` (I'm not super familiar with how groovy figures these casts out), but instead, in some situations, groovy decides to try and cast by first converting to a `String`. If anything, I'd suspect a bug in groovy, since that should happen the same way every single time, and not be based on what was executed before.

**Comment by cokieffebah** [comment] 2022-01-26 22:01
actually, now that I look again, that line I shared is probably the issue.  
you can not cast a Set to List, they are different interfaces

**Comment by serpa-dystematic** [comment] 2022-02-23 17:36
@andrewm-aero did you solve this? I'm getting the same error for one repository only. All other 50 are ok :/ 
This started yesterday and I didn't make any change that I think could have affected this.

**Comment by cokieffebah** [comment] 2022-02-23 17:56
yeah, we need to a new release with this update.
I added this branch: ghi-250-gcv-assignment-fix.  Need to run tests and other things

**Comment by cokieffebah** [comment] 2022-02-23 17:58
@andrewm-aero can you submit a PR for this fix.  thanks

**Comment by cokieffebah** [comment] 2022-02-25 14:29
@andrewm-aero ^ that's if you want the credit in the commits ... I am fine with committing my fix once I create some tests

**Comment by serpa-dystematic** [comment] 2022-02-28 12:26
Can we have a bugfix release on 2.2 version?
We have at least an issue that doesn't let us move to 2.3: https://github.com/jenkinsci/templating-engine-plugin/issues/225

**Comment by steven-terrana** [comment] 2022-02-28 14:20
Jenkins plugin releases are immutable.
It's not possible to update a previously released version.

**Comment by serpa-dystematic** [comment] 2022-02-28 15:23
Hey @steven-terrana, I was saying to release a 2.2.3, not updating the 2.2.2.
Still, idk if it's possible.
Thanks.

**Closed** 2022-05-25 23:04 UTC
Labels: bug
